base:
  dataset: AmassDiscreteDataset
  model: HumorDiffusion
  loss: HumorLoss
  out: /content/drive/MyDrive/DiffuMoR/out/diffusion_train
  gpu: 0
  batch_size: 200
  epochs: 200
  lr: 0.0001
  sched_milestones: [50, 80, 140]
  sched_decay: 0.5
  sched_samp_start: 10
  sched_samp_end: 20
  val_every: 2
  save_every: 25
  print_every: 10

dataset:
  data_paths: 
    - /content/datasets/AMASS/amass_processed
  split_by: sequence
  sample_num_frames: 10
  step_frames_in: 1
  step_frames_out: 1
  data_rot_rep: mat
  data_return_config: smpl+joints+contacts
  deterministic_train: True
  diffusion_base_channels': 64,
  'diffusion_embed_dim': 256,
  'diffusion_num_layers': 4,
  'encoder_hidden_size': 1024,
  'encoder_num_layers': 4,
  'decoder_hidden_size': 1024,
  'decoder_num_layers': 4,

model:
  model_data_config: smpl+joints+contacts
  in_rot_rep: mat
  out_rot_rep: aa
  latent_size: 48
  steps_in: 1

loss:
  kl_loss: 0.0
  kl_loss_anneal_start: 0
  kl_loss_anneal_end: 50
  contacts_loss: 0.01
  contacts_vel_loss: 0.01
  regr_trans_loss: 1.0
  regr_trans_vel_loss: 1.0
  regr_root_orient_loss: 1.0
  regr_root_orient_vel_loss: 1.0
  regr_pose_loss: 1.0
  regr_pose_vel_loss: 1.0
  regr_joint_loss: 1.0
  regr_joint_vel_loss: 1.0
  regr_joint_orient_vel_loss: 1.0
  regr_vert_loss: 1.0
  regr_vert_vel_loss: 1.0
  smpl_joint_loss: 1.0
  smpl_mesh_loss: 1.0
  smpl_joint_consistency_loss: 1.0