base:
  # === Data and Model Paths ===
  data_path: ../datasets/AMASS/amass_processed
  data_type: AMASS
  data_fps: 30
  model: DreamorDiffusionTransformer
  

  smpl: ./body_models/smplh/neutral/model.npz
  ckpt: ./out/humordiffusiontransformer_train/20250507_040645/checkpoints/best_model.pth
  out: ./out/eval/128_full_stage3_ddimstep10_bestmodel

  # === AMASS Options ===
  amass_split_by: sequence
  shuffle: false
  amass_batch_size: 1
  amass_seq_len: 60
  amass_use_verts: true
  amass_noise_std: 0.0
  amass_make_partial: true
  amass_partial_height: 0.9

  # === Loss Weights ===
  joint3d_weight: [0.0, 0.0, 0.0]
  vert3d_weight: [1.0, 1.0, 1.0]
  point3d_weight: [0.0, 0.0, 0.0]
  pose_prior_weight: [0.0002, 0.0002, 0.0]
  shape_prior_weight: [0.000167, 0.000167, 0.000167]
  motion_prior_weight: [0.0, 0.0, 0.0005]
  init_motion_prior_weight: [0.0, 0.0, 0.0]
  joint3d_smooth_weight: [0.1, 0.1, 0.0]
  joint_consistency_weight: [0.0, 0.0, 1.0]
  bone_length_weight: [0.0, 0.0, 10.0]
  contact_vel_weight: [0.0, 0.0, 1.0]
  contact_height_weight: [0.0, 0.0, 1.0]

  # === Optimization ===
  lr: 1.0
  num_iters: [30, 70, 70]

  # === Stage 3 Control ===
  stage3_tune_init_num_frames: 15
  stage3_tune_init_freeze_start: 30
  stage3_tune_init_freeze_end: 55

  # === Misc ===
  gt_body_type: smplh
  save_results: true

model:
  model_data_config: smpl+joints+contacts
  in_rot_rep: mat
  out_rot_rep: aa
  steps_in: 1
  latent_size: 128
  pose_token_dim: 64
  diffusion_base_dim: 256
  nhead: 4
  num_layers: 6
  dim_feedforward: 1024
  dropout: 0.1
  cfg_scale: 4.0
  cond_drop_prob: 0.1
  use_mean_sample: True
  ddim_steps: 10